create table SIGUN (
  si varchar2(6),
  gun varchar2(20)
);

Insert into SIGUN (SI,GUN) values ('서울','강남구');
Insert into SIGUN (SI,GUN) values ('서울','강동구');
Insert into SIGUN (SI,GUN) values ('서울','강북구');
Insert into SIGUN (SI,GUN) values ('서울','강서구');
Insert into SIGUN (SI,GUN) values ('서울','관악구');
Insert into SIGUN (SI,GUN) values ('서울','광진구');
Insert into SIGUN (SI,GUN) values ('서울','구로구');
Insert into SIGUN (SI,GUN) values ('서울','금천구');
Insert into SIGUN (SI,GUN) values ('서울','노원구');
Insert into SIGUN (SI,GUN) values ('서울','도봉구');
Insert into SIGUN (SI,GUN) values ('서울','동대문구');
Insert into SIGUN (SI,GUN) values ('서울','동작구');
Insert into SIGUN (SI,GUN) values ('서울','마포구');
Insert into SIGUN (SI,GUN) values ('서울','서대문구');
Insert into SIGUN (SI,GUN) values ('서울','서초구');
Insert into SIGUN (SI,GUN) values ('서울','성동구');
Insert into SIGUN (SI,GUN) values ('서울','성북구');
Insert into SIGUN (SI,GUN) values ('서울','송파구');
Insert into SIGUN (SI,GUN) values ('서울','양천구');
Insert into SIGUN (SI,GUN) values ('서울','영등포구');
Insert into SIGUN (SI,GUN) values ('서울','용산구');
Insert into SIGUN (SI,GUN) values ('서울','은평구');
Insert into SIGUN (SI,GUN) values ('서울','종로구');
Insert into SIGUN (SI,GUN) values ('서울','중구');
Insert into SIGUN (SI,GUN) values ('서울','중랑구');
Insert into SIGUN (SI,GUN) values ('부산','강서구');
Insert into SIGUN (SI,GUN) values ('부산','금정구');
Insert into SIGUN (SI,GUN) values ('부산','남구');
Insert into SIGUN (SI,GUN) values ('부산','동구');
Insert into SIGUN (SI,GUN) values ('부산','동래구');
Insert into SIGUN (SI,GUN) values ('부산','부산진구');
Insert into SIGUN (SI,GUN) values ('부산','북구');
Insert into SIGUN (SI,GUN) values ('부산','사상구');
Insert into SIGUN (SI,GUN) values ('부산','사하구');
Insert into SIGUN (SI,GUN) values ('부산','서구');
Insert into SIGUN (SI,GUN) values ('부산','수영구');
Insert into SIGUN (SI,GUN) values ('부산','연제구');
Insert into SIGUN (SI,GUN) values ('부산','영도구');
Insert into SIGUN (SI,GUN) values ('부산','중구');
Insert into SIGUN (SI,GUN) values ('부산','해운대구');
Insert into SIGUN (SI,GUN) values ('부산','기장군');
Insert into SIGUN (SI,GUN) values ('대구','남구');
Insert into SIGUN (SI,GUN) values ('대구','달서구');
Insert into SIGUN (SI,GUN) values ('대구','동구');
Insert into SIGUN (SI,GUN) values ('대구','북구');
Insert into SIGUN (SI,GUN) values ('대구','서구');
Insert into SIGUN (SI,GUN) values ('대구','수성구');
Insert into SIGUN (SI,GUN) values ('대구','중구');
Insert into SIGUN (SI,GUN) values ('대구','달성군');
Insert into SIGUN (SI,GUN) values ('인천','계양구');
Insert into SIGUN (SI,GUN) values ('인천','남구');
Insert into SIGUN (SI,GUN) values ('인천','남동구');
Insert into SIGUN (SI,GUN) values ('인천','동구');
Insert into SIGUN (SI,GUN) values ('인천','부평구');
Insert into SIGUN (SI,GUN) values ('인천','서구');
Insert into SIGUN (SI,GUN) values ('인천','연수구');
Insert into SIGUN (SI,GUN) values ('인천','중구');
Insert into SIGUN (SI,GUN) values ('인천','강화군');
Insert into SIGUN (SI,GUN) values ('인천','옹진군');
Insert into SIGUN (SI,GUN) values ('광주','광산구');
Insert into SIGUN (SI,GUN) values ('광주','남구');
Insert into SIGUN (SI,GUN) values ('광주','동구');
Insert into SIGUN (SI,GUN) values ('광주','북구');
Insert into SIGUN (SI,GUN) values ('광주','서구');
Insert into SIGUN (SI,GUN) values ('대전','대덕구');
Insert into SIGUN (SI,GUN) values ('대전','동구');
Insert into SIGUN (SI,GUN) values ('대전','서구');
Insert into SIGUN (SI,GUN) values ('대전','유성구');
Insert into SIGUN (SI,GUN) values ('대전','중구');
Insert into SIGUN (SI,GUN) values ('울산','남구');
Insert into SIGUN (SI,GUN) values ('울산','동구');
Insert into SIGUN (SI,GUN) values ('울산','북구');
Insert into SIGUN (SI,GUN) values ('울산','중구');
Insert into SIGUN (SI,GUN) values ('울산','울주군');
Insert into SIGUN (SI,GUN) values ('세종',null);
Insert into SIGUN (SI,GUN) values ('강원','강릉시');
Insert into SIGUN (SI,GUN) values ('강원','동해시');
Insert into SIGUN (SI,GUN) values ('강원','삼척시');
Insert into SIGUN (SI,GUN) values ('강원','속초시');
Insert into SIGUN (SI,GUN) values ('강원','원주시');
Insert into SIGUN (SI,GUN) values ('강원','춘천시');
Insert into SIGUN (SI,GUN) values ('강원','태백시');
Insert into SIGUN (SI,GUN) values ('강원','고성군');
Insert into SIGUN (SI,GUN) values ('강원','양구군');
Insert into SIGUN (SI,GUN) values ('강원','양양군');
Insert into SIGUN (SI,GUN) values ('강원','영월군');
Insert into SIGUN (SI,GUN) values ('강원','인제군');
Insert into SIGUN (SI,GUN) values ('강원','정선군');
Insert into SIGUN (SI,GUN) values ('강원','철원군');
Insert into SIGUN (SI,GUN) values ('강원','평창군');
Insert into SIGUN (SI,GUN) values ('강원','홍천군');
Insert into SIGUN (SI,GUN) values ('강원','화천군');
Insert into SIGUN (SI,GUN) values ('강원','횡성군');
Insert into SIGUN (SI,GUN) values ('경기','고양시 덕양구');
Insert into SIGUN (SI,GUN) values ('경기','고양시 일산동구');
Insert into SIGUN (SI,GUN) values ('경기','고양시 일산서구');
Insert into SIGUN (SI,GUN) values ('경기','과천시');
Insert into SIGUN (SI,GUN) values ('경기','광명시');
Insert into SIGUN (SI,GUN) values ('경기','광주시');
Insert into SIGUN (SI,GUN) values ('경기','구리시');
Insert into SIGUN (SI,GUN) values ('경기','군포시');
Insert into SIGUN (SI,GUN) values ('경기','김포시');
Insert into SIGUN (SI,GUN) values ('경기','남양주시');
Insert into SIGUN (SI,GUN) values ('경기','동두천시');
Insert into SIGUN (SI,GUN) values ('경기','부천시 소사구');
Insert into SIGUN (SI,GUN) values ('경기','부천시 오정구');
Insert into SIGUN (SI,GUN) values ('경기','부천시 원미구');
Insert into SIGUN (SI,GUN) values ('경기','성남시 분당구');
Insert into SIGUN (SI,GUN) values ('경기','성남시 수정구');
Insert into SIGUN (SI,GUN) values ('경기','성남시 중원구');
Insert into SIGUN (SI,GUN) values ('경기','수원시 권선구');
Insert into SIGUN (SI,GUN) values ('경기','수원시 영통구');
Insert into SIGUN (SI,GUN) values ('경기','수원시 장안구');
Insert into SIGUN (SI,GUN) values ('경기','수원시 팔달구');
Insert into SIGUN (SI,GUN) values ('경기','시흥시');
Insert into SIGUN (SI,GUN) values ('경기','안산시 단원구');
Insert into SIGUN (SI,GUN) values ('경기','안산시 상록구');
Insert into SIGUN (SI,GUN) values ('경기','안성시');
Insert into SIGUN (SI,GUN) values ('경기','안양시 동안구');
Insert into SIGUN (SI,GUN) values ('경기','안양시 만안구');
Insert into SIGUN (SI,GUN) values ('경기','양주시');
Insert into SIGUN (SI,GUN) values ('경기','오산시');
Insert into SIGUN (SI,GUN) values ('경기','용인시 기흥구');
Insert into SIGUN (SI,GUN) values ('경기','용인시 수지구');
Insert into SIGUN (SI,GUN) values ('경기','용인시 처인구');
Insert into SIGUN (SI,GUN) values ('경기','의왕시');
Insert into SIGUN (SI,GUN) values ('경기','의정부시');
Insert into SIGUN (SI,GUN) values ('경기','이천시');
Insert into SIGUN (SI,GUN) values ('경기','파주시');
Insert into SIGUN (SI,GUN) values ('경기','평택시');
Insert into SIGUN (SI,GUN) values ('경기','포천시');
Insert into SIGUN (SI,GUN) values ('경기','하남시');
Insert into SIGUN (SI,GUN) values ('경기','화성시');
Insert into SIGUN (SI,GUN) values ('경기','가평군');
Insert into SIGUN (SI,GUN) values ('경기','양평군');
Insert into SIGUN (SI,GUN) values ('경기','여주군');
Insert into SIGUN (SI,GUN) values ('경기','연천군');
Insert into SIGUN (SI,GUN) values ('경남','거제시');
Insert into SIGUN (SI,GUN) values ('경남','김해시');
Insert into SIGUN (SI,GUN) values ('경남','밀양시');
Insert into SIGUN (SI,GUN) values ('경남','사천시');
Insert into SIGUN (SI,GUN) values ('경남','양산시');
Insert into SIGUN (SI,GUN) values ('경남','진주시');
Insert into SIGUN (SI,GUN) values ('경남','창원시 마산합포구');
Insert into SIGUN (SI,GUN) values ('경남','창원시 마산회원구');
Insert into SIGUN (SI,GUN) values ('경남','창원시 성산구');
Insert into SIGUN (SI,GUN) values ('경남','창원시 의창구');
Insert into SIGUN (SI,GUN) values ('경남','창원시 진해구');
Insert into SIGUN (SI,GUN) values ('경남','통영시');
Insert into SIGUN (SI,GUN) values ('경남','거창군');
Insert into SIGUN (SI,GUN) values ('경남','고성군');
Insert into SIGUN (SI,GUN) values ('경남','남해군');
Insert into SIGUN (SI,GUN) values ('경남','산청군');
Insert into SIGUN (SI,GUN) values ('경남','의령군');
Insert into SIGUN (SI,GUN) values ('경남','창녕군');
Insert into SIGUN (SI,GUN) values ('경남','하동군');
Insert into SIGUN (SI,GUN) values ('경남','함안군');
Insert into SIGUN (SI,GUN) values ('경남','함양군');
Insert into SIGUN (SI,GUN) values ('경남','합천군');
Insert into SIGUN (SI,GUN) values ('경북','경산시');
Insert into SIGUN (SI,GUN) values ('경북','경주시');
Insert into SIGUN (SI,GUN) values ('경북','구미시');
Insert into SIGUN (SI,GUN) values ('경북','김천시');
Insert into SIGUN (SI,GUN) values ('경북','문경시');
Insert into SIGUN (SI,GUN) values ('경북','상주시');
Insert into SIGUN (SI,GUN) values ('경북','안동시');
Insert into SIGUN (SI,GUN) values ('경북','영주시');
Insert into SIGUN (SI,GUN) values ('경북','영천시');
Insert into SIGUN (SI,GUN) values ('경북','포항시 남구');
Insert into SIGUN (SI,GUN) values ('경북','포항시 북구');
Insert into SIGUN (SI,GUN) values ('경북','고령군');
Insert into SIGUN (SI,GUN) values ('경북','군위군');
Insert into SIGUN (SI,GUN) values ('경북','봉화군');
Insert into SIGUN (SI,GUN) values ('경북','성주군');
Insert into SIGUN (SI,GUN) values ('경북','영덕군');
Insert into SIGUN (SI,GUN) values ('경북','영양군');
Insert into SIGUN (SI,GUN) values ('경북','예천군');
Insert into SIGUN (SI,GUN) values ('경북','울릉군');
Insert into SIGUN (SI,GUN) values ('경북','울진군');
Insert into SIGUN (SI,GUN) values ('경북','의성군');
Insert into SIGUN (SI,GUN) values ('경북','청도군');
Insert into SIGUN (SI,GUN) values ('경북','청송군');
Insert into SIGUN (SI,GUN) values ('경북','칠곡군');
Insert into SIGUN (SI,GUN) values ('전남','광양시');
Insert into SIGUN (SI,GUN) values ('전남','나주시');
Insert into SIGUN (SI,GUN) values ('전남','목포시');
Insert into SIGUN (SI,GUN) values ('전남','순천시');
Insert into SIGUN (SI,GUN) values ('전남','여수시');
Insert into SIGUN (SI,GUN) values ('전남','강진군');
Insert into SIGUN (SI,GUN) values ('전남','고흥군');
Insert into SIGUN (SI,GUN) values ('전남','곡성군');
Insert into SIGUN (SI,GUN) values ('전남','구례군');
Insert into SIGUN (SI,GUN) values ('전남','담양군');
Insert into SIGUN (SI,GUN) values ('전남','무안군');
Insert into SIGUN (SI,GUN) values ('전남','보성군');
Insert into SIGUN (SI,GUN) values ('전남','신안군');
Insert into SIGUN (SI,GUN) values ('전남','영광군');
Insert into SIGUN (SI,GUN) values ('전남','영암군');
Insert into SIGUN (SI,GUN) values ('전남','완도군');
Insert into SIGUN (SI,GUN) values ('전남','장성군');
Insert into SIGUN (SI,GUN) values ('전남','장흥군');
Insert into SIGUN (SI,GUN) values ('전남','진도군');
Insert into SIGUN (SI,GUN) values ('전남','함평군');
Insert into SIGUN (SI,GUN) values ('전남','해남군');
Insert into SIGUN (SI,GUN) values ('전남','화순군');
Insert into SIGUN (SI,GUN) values ('전북','군산시');
Insert into SIGUN (SI,GUN) values ('전북','김제시');
Insert into SIGUN (SI,GUN) values ('전북','남원시');
Insert into SIGUN (SI,GUN) values ('전북','익산시');
Insert into SIGUN (SI,GUN) values ('전북','전주시 덕진구');
Insert into SIGUN (SI,GUN) values ('전북','전주시 완산구');
Insert into SIGUN (SI,GUN) values ('전북','정읍시');
Insert into SIGUN (SI,GUN) values ('전북','고창군');
Insert into SIGUN (SI,GUN) values ('전북','무주군');
Insert into SIGUN (SI,GUN) values ('전북','부안군');
Insert into SIGUN (SI,GUN) values ('전북','순창군');
Insert into SIGUN (SI,GUN) values ('전북','완주군');
Insert into SIGUN (SI,GUN) values ('전북','임실군');
Insert into SIGUN (SI,GUN) values ('전북','장수군');
Insert into SIGUN (SI,GUN) values ('전북','진안군');
Insert into SIGUN (SI,GUN) values ('제주','제주시');
Insert into SIGUN (SI,GUN) values ('제주','서귀포시');
Insert into SIGUN (SI,GUN) values ('충남','계룡시');
Insert into SIGUN (SI,GUN) values ('충남','공주시');
Insert into SIGUN (SI,GUN) values ('충남','논산시');
Insert into SIGUN (SI,GUN) values ('충남','당진시');
Insert into SIGUN (SI,GUN) values ('충남','보령시');
Insert into SIGUN (SI,GUN) values ('충남','서산시');
Insert into SIGUN (SI,GUN) values ('충남','아산시');
Insert into SIGUN (SI,GUN) values ('충남','천안시 동남구');
Insert into SIGUN (SI,GUN) values ('충남','천안시 서북구');
Insert into SIGUN (SI,GUN) values ('충남','금산군');
Insert into SIGUN (SI,GUN) values ('충남','부여군');
Insert into SIGUN (SI,GUN) values ('충남','서천군');
Insert into SIGUN (SI,GUN) values ('충남','예산군');
Insert into SIGUN (SI,GUN) values ('충남','청양군');
Insert into SIGUN (SI,GUN) values ('충남','태안군');
Insert into SIGUN (SI,GUN) values ('충남','홍성군');
Insert into SIGUN (SI,GUN) values ('충북','제천시');
Insert into SIGUN (SI,GUN) values ('충북','청주시 상당구');
Insert into SIGUN (SI,GUN) values ('충북','청주시 흥덕구');
Insert into SIGUN (SI,GUN) values ('충북','충주시');
Insert into SIGUN (SI,GUN) values ('충북','괴산군');
Insert into SIGUN (SI,GUN) values ('충북','단양군');
Insert into SIGUN (SI,GUN) values ('충북','보은군');
Insert into SIGUN (SI,GUN) values ('충북','영동군');
Insert into SIGUN (SI,GUN) values ('충북','옥천군');
Insert into SIGUN (SI,GUN) values ('충북','음성군');
Insert into SIGUN (SI,GUN) values ('충북','증평군');
Insert into SIGUN (SI,GUN) values ('충북','진천군');
Insert into SIGUN (SI,GUN) values ('충북','청원군');

select * from sigun;